/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.PrecoQuartoController;
import model.PrecoQuarto;

import javax.swing.table.DefaultTableModel;
import java.util.List;

import controller.QuartoController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Quarto;
import util.SomenteNumeros;

/**
 *
 * @author manoelpimentel
 */
public class TelaCadastroQuarto extends javax.swing.JInternalFrame {

    private final QuartoController quartoController = new QuartoController();
    private final PrecoQuartoController precoController = new PrecoQuartoController();
    private final java.util.List<PrecoQuarto> precosTemp = new java.util.ArrayList<>();

    /**
     * Creates new form CadastroQuarto
     */
    public TelaCadastroQuarto() {
        initComponents();
    }

    private void preencherTabelaQuartos(List<Quarto> lista) {
        DefaultTableModel model = (DefaultTableModel) tabelaDadosQuarto.getModel();
        model.setRowCount(0);

        for (Quarto q : lista) {

            // buscar preços vinculados
            List<PrecoQuarto> precos = precoController.listarPorQuartoId(q.getId());

            if (precos.isEmpty()) {
                // caso não tenha preços
                model.addRow(new Object[]{
                    q.getId(),
                    q.getNumero(),
                    q.getTipo(),
                    q.getStatus(),
                    q.getNumCamas(),
                    "—",
                    "—",
                    q.getObservacao(),
                    q.getCriadoEm() != null ? q.getCriadoEm() : "—"
                });
            } else {
                // adiciona uma linha para cada preço de ocupação
                for (PrecoQuarto p : precos) {
                    model.addRow(new Object[]{
                        q.getId(),
                        q.getNumero(),
                        q.getTipo(),
                        q.getStatus(),
                        q.getNumCamas(),
                        p.getOcupacao(),
                        p.getPreco(),
                        q.getObservacao(),
                        q.getCriadoEm() != null ? q.getCriadoEm() : "—"
                    });
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        campoNumQuarto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnConsultarQuarto = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnCadastrarQuarto = new javax.swing.JButton();
        btnCadastrarPrecoQuartos = new javax.swing.JButton();
        btnRemoverPreco = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPrecoQuarto = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaObservacao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        numQuarto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboTipoQuarto = new javax.swing.JComboBox<>();
        comboStatusQuarto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNumCamas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSalvarPreCadastroQuarto = new javax.swing.JButton();
        btnAtualizarQuarto = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnExcluirQuarto = new javax.swing.JButton();
        btnEditarQuarto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDadosQuarto = new javax.swing.JTable();

        setClosable(true);
        setTitle("Sistema Hoteleiro - Cadasto Quartos");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Realizar uma consulta pelo numero do quarto antes de fazer um cadastro!");

        SomenteNumeros.aplicar(campoNumQuarto);

        jLabel7.setText("Informe o numero do quarto:");

        btnConsultarQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnConsultarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnConsultarQuarto.setText("Consultar");
        btnConsultarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarQuartoActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 51, 51));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados cadastrais do Quarto"));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnFechar.setBackground(new java.awt.Color(0, 51, 51));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_excluir.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastrarQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnCadastrarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_salvar.png"))); // NOI18N
        btnCadastrarQuarto.setText("Finalizar Cadastrar Quarto");
        btnCadastrarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarQuartoActionPerformed(evt);
            }
        });

        btnCadastrarPrecoQuartos.setBackground(new java.awt.Color(0, 51, 51));
        btnCadastrarPrecoQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_recebe.png"))); // NOI18N
        btnCadastrarPrecoQuartos.setText("Cadastrar Preco Quartos");
        btnCadastrarPrecoQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPrecoQuartosActionPerformed(evt);
            }
        });

        btnRemoverPreco.setBackground(new java.awt.Color(0, 51, 51));
        btnRemoverPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_excluir.png"))); // NOI18N
        btnRemoverPreco.setText("Remover Preço");
        btnRemoverPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarPrecoQuartos)
                .addGap(50, 50, 50)
                .addComponent(btnRemoverPreco)
                .addGap(50, 50, 50)
                .addComponent(btnCadastrarQuarto)
                .addGap(50, 50, 50)
                .addComponent(btnFechar)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrarQuarto)
                    .addComponent(btnCadastrarPrecoQuartos)
                    .addComponent(btnRemoverPreco))
                .addContainerGap())
        );

        tabelaPrecoQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ocupação (Hospede)", "Preços Quarto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaPrecoQuarto);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        areaObservacao.setColumns(20);
        areaObservacao.setRows(5);
        jScrollPane1.setViewportView(areaObservacao);

        jLabel5.setText("Observações:");

        SomenteNumeros.aplicar(numQuarto);

        jLabel4.setText("Nº Quarto:");

        comboTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Simples", "Duplo", "Suíte" }));

        comboStatusQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Disponível", "Ocupado", "Bloqueado" }));

        jLabel1.setText("Tipo Quarto:");

        jLabel3.setText("Status:");

        SomenteNumeros.aplicar(campoNumCamas);

        jLabel2.setText("Nº Camas:");

        btnSalvarPreCadastroQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnSalvarPreCadastroQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_salvar.png"))); // NOI18N
        btnSalvarPreCadastroQuarto.setText("Salvar Pré-Cadastro");
        btnSalvarPreCadastroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPreCadastroQuartoActionPerformed(evt);
            }
        });

        btnAtualizarQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnAtualizarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.png"))); // NOI18N
        btnAtualizarQuarto.setText("Atualizar Quarto");
        btnAtualizarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboStatusQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNumCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jScrollPane1))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvarPreCadastroQuarto)
                    .addComponent(btnAtualizarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStatusQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAtualizarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvarPreCadastroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnExcluirQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnExcluirQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_excluir.png"))); // NOI18N
        btnExcluirQuarto.setText("Excluir");
        btnExcluirQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirQuartoActionPerformed(evt);
            }
        });

        btnEditarQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnEditarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.png"))); // NOI18N
        btnEditarQuarto.setText("Editar");
        btnEditarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarQuartoActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Para editar e excluir selecione na tabela e cilque em um dos butom!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarQuarto)
                .addGap(27, 27, 27)
                .addComponent(btnExcluirQuarto)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirQuarto)
                    .addComponent(btnEditarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        tabelaDadosQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NUN. QUARTO", "TIPO", "STATUS", "NUM. CAMAS", "OCUPAÇÃO", "PREÇO", "CRIADO EM", "OBSERVAÇÕES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaDadosQuarto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jScrollPane4.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                .addComponent(btnConsultarQuarto)
                .addGap(47, 47, 47)
                .addComponent(btnLimpar)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultarQuarto)
                        .addComponent(btnLimpar))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnConsultarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarQuartoActionPerformed
        // TODO add your handling code here:
        try {
            if (campoNumQuarto.getText().isBlank()) {
                preencherTabelaQuartos(quartoController.listarTodos());
                return;
            }
            int numero = Integer.parseInt(campoNumQuarto.getText().trim());
            Quarto q = quartoController.buscarPorNumero(numero);
            if (q != null) {
                preencherTabelaQuartos(List.of(q));
            } else {
                JOptionPane.showMessageDialog(this, "Quarto não encontrado.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Número do quarto inválido.");
        }
    }//GEN-LAST:event_btnConsultarQuartoActionPerformed

    private void btnEditarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarQuartoActionPerformed
        // TODO add your handling code here:
        int linha = tabelaDadosQuarto.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um quarto para editar!");
            return;
        }
        int id = (int) tabelaDadosQuarto.getValueAt(linha, 0);
        Quarto q = quartoController.buscarPorId(id);
        if (q != null) {
            numQuarto.setText(String.valueOf(q.getNumero()));
            comboTipoQuarto.setSelectedItem(q.getTipo());
            comboStatusQuarto.setSelectedItem(q.getStatus());
            campoNumCamas.setText(String.valueOf(q.getNumCamas()));
            areaObservacao.setText(q.getObservacao());
            // store id somewhere (ex.: campo oculto) para atualizar
            numQuarto.putClientProperty("editingId", q.getId());
        }
    }//GEN-LAST:event_btnEditarQuartoActionPerformed

    private void btnExcluirQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirQuartoActionPerformed
        // TODO add your handling code here:

        int linha = tabelaDadosQuarto.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um quarto na tabela!");
            return;
        }

        int idQuarto = (int) tabelaDadosQuarto.getValueAt(linha, 0);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir este quarto?\nOs preços vinculados também serão removidos.",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            QuartoController controller = new QuartoController();
            if (controller.excluirQuartoIfDisponivel(idQuarto)) {
                JOptionPane.showMessageDialog(this, "Quarto excluído com sucesso!");
                // recarregar tabela
            } else {
                JOptionPane.showMessageDialog(this,
                        "Não foi possível excluir.\nVerifique se o quarto está DISPONÍVEL.");
            }
        }

    }//GEN-LAST:event_btnExcluirQuartoActionPerformed

    private void btnSalvarPreCadastroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPreCadastroQuartoActionPerformed
        // TODO add your handling code here:
        try {
            Quarto q = new Quarto();
            q.setNumero(Integer.parseInt(numQuarto.getText().trim()));
            q.setTipo(comboTipoQuarto.getSelectedItem().toString());
            q.setNumCamas(Integer.parseInt(campoNumCamas.getText().trim()));
            q.setStatus(comboStatusQuarto.getSelectedItem().toString());
            q.setObservacao(areaObservacao.getText());

            // SALVA E RETORNA ID
            int idGerado = quartoController.cadastrarRetornandoId(q);

            if (idGerado <= 0) {
                JOptionPane.showMessageDialog(this, "Erro ao realizar pré-cadastro.");
                return;
            }

            // GUARDA O ID DO PRÉ-CADASTRO!!!
            numQuarto.putClientProperty("preCadastroId", idGerado);

            JOptionPane.showMessageDialog(this,
                    "Pré-cadastro realizado com sucesso! ID: " + idGerado);

            preencherTabelaQuartos(quartoController.listarTodos());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSalvarPreCadastroQuartoActionPerformed

    private void btnAtualizarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarQuartoActionPerformed
        // TODO add your handling code here:
        Object obj = numQuarto.getClientProperty("editingId");
        if (obj == null) {
            JOptionPane.showMessageDialog(this, "Nenhum quarto em edição. Selecione um e clique em Editar.");
            return;
        }
        try {
            int id = (int) obj;
            Quarto q = new Quarto();
            q.setId(id);
            q.setNumero(Integer.parseInt(numQuarto.getText().trim()));
            q.setTipo(comboTipoQuarto.getSelectedItem().toString());
            q.setNumCamas(Integer.parseInt(campoNumCamas.getText().trim()));
            q.setStatus(comboStatusQuarto.getSelectedItem().toString());
            q.setObservacao(areaObservacao.getText());

            boolean ok = quartoController.atualizarQuarto(q);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Quarto atualizado com sucesso!");
                preencherTabelaQuartos(quartoController.listarTodos());
                numQuarto.putClientProperty("editingId", null);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar quarto.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarQuartoActionPerformed

    private void btnCadastrarPrecoQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPrecoQuartosActionPerformed
        // TODO add your handling code here:
        JTextField txtOcupacao = new JTextField();
        JTextField txtPreco = new JTextField();

        Object[] campos = {
            "Ocupação (Qtd. hóspedes):", txtOcupacao,
            "Preço da diária (R$):", txtPreco
        };

        int opcao = JOptionPane.showOptionDialog(
                this,
                campos,
                "Adicionar Preço ao Quarto",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                new Object[]{"Adicionar Preço", "Cancelar"},
                "Adicionar Preço"
        );

        if (opcao != 0) {
            return;
        }

        if (txtOcupacao.getText().isEmpty()
                || txtPreco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }

        try {
            int ocupacao = Integer.parseInt(txtOcupacao.getText());
            double preco = Double.parseDouble(txtPreco.getText().replace(",", "."));

            PrecoQuarto pq = new PrecoQuarto();
            pq.setOcupacao(ocupacao);
            pq.setPreco(preco);

            precosTemp.add(pq);

            DefaultTableModel model = (DefaultTableModel) tabelaPrecoQuarto.getModel();
            model.addRow(new Object[]{ocupacao, preco});

            JOptionPane.showMessageDialog(this,
                    "Preço adicionado! (Ainda não salvo no banco)");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Valores inválidos.");
        }

    }//GEN-LAST:event_btnCadastrarPrecoQuartosActionPerformed

    private void btnCadastrarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarQuartoActionPerformed
        // TODO add your handling code here:

        Object obj = numQuarto.getClientProperty("preCadastroId");

        if (obj == null) {
            JOptionPane.showMessageDialog(this,
                    "Você precisa realizar o PRÉ-CADASTRO antes de finalizar!");
            return;
        }

        int idQuarto = (int) obj;

        try {
            // SALVAR PREÇOS VINCULADOS AO QUARTO
            for (PrecoQuarto pq : precosTemp) {
                pq.setQuartoId(idQuarto);
                precoController.cadastrar(pq);
            }

            JOptionPane.showMessageDialog(this,
                    "Cadastro finalizado com sucesso!");

            precosTemp.clear();
            ((DefaultTableModel) tabelaPrecoQuarto.getModel()).setRowCount(0);

            numQuarto.putClientProperty("preCadastroId", null);

            preencherTabelaQuartos(quartoController.listarTodos());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }

    }//GEN-LAST:event_btnCadastrarQuartoActionPerformed

    private void btnRemoverPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPrecoActionPerformed
        // TODO add your handling code here:
        int linha = tabelaPrecoQuarto.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um preço na tabela para remover!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente remover este preço?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            // REMOVE DA LISTA TEMPORÁRIA
            precosTemp.remove(linha);

            // REMOVE DA TABELA VISUAL
            DefaultTableModel model = (DefaultTableModel) tabelaPrecoQuarto.getModel();
            model.removeRow(linha);

            JOptionPane.showMessageDialog(this, "Preço removido com sucesso!");
        }

    }//GEN-LAST:event_btnRemoverPrecoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void limparCampos() {

        // Campos de texto
        numQuarto.setText("");
        campoNumCamas.setText("");
        campoNumQuarto.setText("");
        areaObservacao.setText("");

        // Combos
        comboTipoQuarto.setSelectedIndex(0);
        comboStatusQuarto.setSelectedIndex(0);

        // Remove ID de edição (caso exista)
        numQuarto.putClientProperty("editingId", null);

        // Limpa tabela de preços
        DefaultTableModel modelPrecos = (DefaultTableModel) tabelaPrecoQuarto.getModel();
        modelPrecos.setRowCount(0);

        // Limpa lista temporária
        precosTemp.clear();

        // Limpa tabela de consulta de quartos
        DefaultTableModel modelQuartos = (DefaultTableModel) tabelaDadosQuarto.getModel();
        modelQuartos.setRowCount(0);

        // Mensagem opcional
        // JOptionPane.showMessageDialog(this, "Campos limpos!");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaObservacao;
    private javax.swing.JButton btnAtualizarQuarto;
    private javax.swing.JButton btnCadastrarPrecoQuartos;
    private javax.swing.JButton btnCadastrarQuarto;
    private javax.swing.JButton btnConsultarQuarto;
    private javax.swing.JButton btnEditarQuarto;
    private javax.swing.JButton btnExcluirQuarto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemoverPreco;
    private javax.swing.JButton btnSalvarPreCadastroQuarto;
    private javax.swing.JTextField campoNumCamas;
    private javax.swing.JTextField campoNumQuarto;
    private javax.swing.JComboBox<String> comboStatusQuarto;
    private javax.swing.JComboBox<String> comboTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField numQuarto;
    private javax.swing.JTable tabelaDadosQuarto;
    private javax.swing.JTable tabelaPrecoQuarto;
    // End of variables declaration//GEN-END:variables
}
