/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import model.PagamentoFuncionario;
import javax.swing.table.DefaultTableModel;
import controller.PagamentoFuncionarioController;
import dao.FuncionarioDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import model.Funcionario;
import java.util.List;
import util.CampoMoeda;
import util.UsuarioLogado;

/**
 *
 * @author manoelpimentel
 */
public class TelaLiberarPagamentoSalario extends javax.swing.JInternalFrame {

    private final PagamentoFuncionarioController controller = new PagamentoFuncionarioController();

    /**
     * Creates new form ConsultarSalario
     */
    public TelaLiberarPagamentoSalario() {
        initComponents();
        FuncionarioDAO.atualizarStatusAutomatico();
        //controller.atualizarPagamentosVencidos();
    }

    private void preencherTabela(List<Funcionario> lista) {
        DefaultTableModel model = (DefaultTableModel) tableSalarioFuncionarios.getModel();
        model.setRowCount(0);
        for (Funcionario f : lista) {
            model.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCpf(),
                f.getCargo(),
                f.getStatus(),
                f.getSalario(),
                f.getStatus_pag_salario(),
                f.getData_liberacao_salario() != null ? f.getData_liberacao_salario() : "—"
            });
        }
    }

    // 
    private double lerValorDeLabel(javax.swing.JLabel label) {
        if (label == null) {
            return 0.0;
        }
        String txt = label.getText();
        if (txt == null || txt.isBlank()) {
            return 0.0;
        }

        // remove tudo que não seja dígito, vírgula ou ponto ou sinal
        txt = txt.trim().replaceAll("[^0-9,\\.-]", "");

        // Se contém vírgula (formato pt-BR): remover pontos de milhar e trocar vírgula por ponto
        if (txt.contains(",")) {
            txt = txt.replace(".", "");      // remove separador de milhares
            txt = txt.replace(",", ".");     // transforma decimal
        }
        // Agora txt está no formato 1234.56 ou 500.0
        try {
            return Double.parseDouble(txt);
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    private void calcularSalarioFinal() {
        // lê salário base do JLabel (pode vir com "R$ " ou sem)
        double salarioBase = lerValorDeLabel(campoSalario);

        // lê aumento e desconto (sua classe CampoMoeda fornece o double corretamente)
        double aumento = CampoMoeda.getValor(campoAumento);
        double desconto = CampoMoeda.getValor(campoDesconto);

        // cálculo final: salárioBase + aumento - desconto
        double salarioFinal = salarioBase + aumento - desconto;

        // exibe formatado no JLabel campoSalarioFinal
        campoSalarioFinal.setText(String.format("R$ %.2f", salarioFinal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoConsultarCpf = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        panelpagamento = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelDadosFuncionario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNome = new javax.swing.JLabel();
        campoCargo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoStatusFuncionario = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        campoSalario = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        comboStatusSalario = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        campoAumento = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        campoDesconto = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        campoSalarioFinal = new javax.swing.JLabel();
        dateDataLiberacao = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnFinalizarPagamento = new javax.swing.JButton();
        btnHistoricoPagamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalarioFuncionarios = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnLiberarSalario = new javax.swing.JButton();
        checkListarTodosFuncionarios = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Sistema Hoteleiro - Consultar e Liberar Pagamentos de Salario");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulte a data de liberação do salario informando o CPF!");

        jLabel2.setText("Informe o CPF:");

        try {
            campoConsultarCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnConsultar.setBackground(new java.awt.Color(0, 51, 51));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 51, 51));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        panelpagamento.setBackground(new java.awt.Color(153, 153, 153));
        panelpagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("ID");

        campoID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoID.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("CPF");

        campoCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoCpf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("NOME");

        campoNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoNome.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        campoCargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoCargo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setText("CARGO");

        jLabel12.setText("STATUS FUNCIONARIO");

        campoStatusFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoStatusFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel18.setText("SALÁRIO");

        campoSalario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoSalario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setText("STATUS PAGAMENTO");

        comboStatusSalario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "PENDENTE", "LIBERADO" }));

        jLabel29.setText("AUMENTO");

        CampoMoeda.aplicar(campoAumento); // Aplica a class que so permite digita valores do tipo moeda brasil
        campoAumento.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                calcularSalarioFinal();
            }
        });

        jLabel30.setText("DESCONTOS");

        CampoMoeda.aplicar(campoDesconto); // Aplica a class que so permite digita valores do tipo moeda brasil
        campoDesconto.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                calcularSalarioFinal();
            }
        });

        jLabel31.setText("SALÁRIO LIQUIDO");

        campoSalarioFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoSalarioFinal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel33.setText("DATA LIBERAÇÃO");

        javax.swing.GroupLayout panelDadosFuncionarioLayout = new javax.swing.GroupLayout(panelDadosFuncionario);
        panelDadosFuncionario.setLayout(panelDadosFuncionarioLayout);
        panelDadosFuncionarioLayout.setHorizontalGroup(
            panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(86, 86, 86)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoStatusFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69))
                    .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboStatusSalario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoAumento)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDesconto)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoSalarioFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateDataLiberacao, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(67, Short.MAX_VALUE))))
        );
        panelDadosFuncionarioLayout.setVerticalGroup(
            panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(campoStatusFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboStatusSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoAumento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateDataLiberacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        btnFechar.setBackground(new java.awt.Color(0, 51, 51));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_excluir.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnFinalizarPagamento.setBackground(new java.awt.Color(0, 51, 51));
        btnFinalizarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_paga.png"))); // NOI18N
        btnFinalizarPagamento.setText("Finalizar Pagamento");
        btnFinalizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPagamentoActionPerformed(evt);
            }
        });

        btnHistoricoPagamento.setBackground(new java.awt.Color(0, 51, 51));
        btnHistoricoPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_consulta.png"))); // NOI18N
        btnHistoricoPagamento.setText("Historico de Pagamento");
        btnHistoricoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoPagamentoActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aqui você pode consultar, liberar e dar Baixa em pamentos!");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistoricoPagamento)
                .addGap(50, 50, 50)
                .addComponent(btnFinalizarPagamento)
                .addGap(50, 50, 50)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnFinalizarPagamento)
                    .addComponent(btnHistoricoPagamento)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDadosFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDadosFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableSalarioFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "CARGO", "STATUS", "SALARIO", "STATUS_PAGAMENTO", "DATA LIBERAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSalarioFuncionarios);

        jPanel8.setForeground(new java.awt.Color(51, 51, 55));

        btnLiberarSalario.setBackground(new java.awt.Color(0, 51, 51));
        btnLiberarSalario.setText("Realizar Pagameto");
        btnLiberarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarSalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLiberarSalario)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLiberarSalario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelpagamentoLayout = new javax.swing.GroupLayout(panelpagamento);
        panelpagamento.setLayout(panelpagamentoLayout);
        panelpagamentoLayout.setHorizontalGroup(
            panelpagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(23, 23, 23))
        );
        panelpagamentoLayout.setVerticalGroup(
            panelpagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpagamentoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        checkListarTodosFuncionarios.setText("Listar Todos Funcionarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoConsultarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(checkListarTodosFuncionarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGap(50, 50, 50)
                        .addComponent(btnLimpar))
                    .addComponent(panelpagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultar)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoConsultarCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkListarTodosFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(panelpagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:                                            
        try {
            if (checkListarTodosFuncionarios.isSelected()) {
                preencherTabela(controller.listarTodos());
            } else {
                String cpf = campoConsultarCpf.getText();
                if (cpf.trim().equals("   .   .   -  ")) {
                    JOptionPane.showMessageDialog(this,
                            "Informe um CPF para consultar!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Funcionario f = controller.buscarPorCpf(cpf);
                if (f != null) {
                    preencherTabela(List.of(f));
                } else {
                    JOptionPane.showMessageDialog(this, "Funcionário não encontrado!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro na consulta: " + e.getMessage());
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnHistoricoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoPagamentoActionPerformed
        // TODO add your handling code here:                                                     
        JOptionPane.showMessageDialog(this,
                    "Metodo ainda não implementado!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        // ação emitir o historico
    }//GEN-LAST:event_btnHistoricoPagamentoActionPerformed

    private void btnFinalizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPagamentoActionPerformed
        // TODO add your handling code here:                                                    
        try {

            int idFuncionario = Integer.parseInt(campoID.getText());
            double salarioBase = Double.parseDouble(campoSalario.getText());

            double aumento = CampoMoeda.getValor(campoAumento);
            double desconto = CampoMoeda.getValor(campoDesconto);
            double salarioFinal = salarioBase + aumento - desconto;

            LocalDate dataLiberacao = dateDataLiberacao.getDate()
                    .toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            String status = comboStatusSalario.getSelectedItem().toString();

            // Extrair mês e ano (necessário para evitar duplicidade)
            int mes = dataLiberacao.getMonthValue();
            int ano = dataLiberacao.getYear();

            if (controller.existePagamentoNoPeriodo(idFuncionario, mes, ano)) {
                JOptionPane.showMessageDialog(this,
                        "Já existe um pagamento liberado para este funcionário neste mês!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Funcionario funcionario = controller.buscarPorId(idFuncionario);
            if (funcionario == null) {
                JOptionPane.showMessageDialog(this,
                        "Funcionário não encontrado no banco!",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            funcionario.setStatus_pag_salario(status);
            funcionario.setData_liberacao_salario(dataLiberacao);

            Funcionario responsavel = UsuarioLogado.getUsuario();
            if (responsavel == null) {
                JOptionPane.showMessageDialog(this,
                        "Nenhum usuário logado encontrado!",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            PagamentoFuncionario pagamento = new PagamentoFuncionario();
            pagamento.setFuncionario(funcionario);
            pagamento.setAumento(aumento);
            pagamento.setDesconto(desconto);
            pagamento.setValorPago(salarioFinal);
            pagamento.setDataLiberacao(dataLiberacao);
            pagamento.setDataEfetuado(LocalDateTime.now());
            pagamento.setStatusPagamento(status);
            pagamento.setResponsavel(responsavel);

            controller.registrarPagamento(pagamento);

            controller.atualizarStatusPagamento(funcionario);

            JOptionPane.showMessageDialog(this,
                    "Pagamento registrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            preencherTabela(controller.listarTodos());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao finalizar pagamento: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnFinalizarPagamentoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        dispose(); // Fechar a tela
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnLiberarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarSalarioActionPerformed
        // TODO add your handling code here:

        int linhaSelecionada = tableSalarioFuncionarios.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um funcionário na tabela primeiro!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Pegar dados da tabela
        int id = (int) tableSalarioFuncionarios.getValueAt(linhaSelecionada, 0);
        String nome = tableSalarioFuncionarios.getValueAt(linhaSelecionada, 1).toString();
        String cpf = tableSalarioFuncionarios.getValueAt(linhaSelecionada, 2).toString();
        String cargo = tableSalarioFuncionarios.getValueAt(linhaSelecionada, 3).toString();
        String status = tableSalarioFuncionarios.getValueAt(linhaSelecionada, 4).toString();
        double salario = Double.parseDouble(tableSalarioFuncionarios.getValueAt(linhaSelecionada, 5).toString());

        // Preenche os campos do painel
        campoID.setText(String.valueOf(id));
        campoNome.setText(nome);
        campoCpf.setText(cpf);
        campoCargo.setText(cargo);
        campoStatusFuncionario.setText(status);
        campoSalario.setText(String.valueOf(salario));
        comboStatusSalario.setSelectedItem("PENDENTE");

        // Define data de liberação padrão (hoje)
        dateDataLiberacao.setDate(new Date());

        JOptionPane.showMessageDialog(this, "Dados do funcionário carregados. Informe aumento, desconto e finalize o pagamento.", "Informação", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnLiberarSalarioActionPerformed

    private void limparCampos() {
        campoNome.setText("");
        campoCpf.setText("");
        campoID.setText("");
        campoCargo.setText("");
        campoStatusFuncionario.setText("");
        campoSalario.setText("");
        comboStatusSalario.setSelectedIndex(0);
        campoConsultarCpf.setText("");
        campoAumento.setText("");
        campoDesconto.setText("");
        campoSalarioFinal.setText("");
        dateDataLiberacao.setDate(null);
        DefaultTableModel model = (DefaultTableModel) tableSalarioFuncionarios.getModel();
        model.setRowCount(0);
        checkListarTodosFuncionarios.setSelected(false);
    }

    // private double salarioBaseAtual = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFinalizarPagamento;
    private javax.swing.JButton btnHistoricoPagamento;
    private javax.swing.JButton btnLiberarSalario;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JTextField campoAumento;
    private javax.swing.JLabel campoCargo;
    private javax.swing.JFormattedTextField campoConsultarCpf;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JTextField campoDesconto;
    private javax.swing.JLabel campoID;
    private javax.swing.JLabel campoNome;
    private javax.swing.JLabel campoSalario;
    private javax.swing.JLabel campoSalarioFinal;
    private javax.swing.JLabel campoStatusFuncionario;
    private javax.swing.JCheckBox checkListarTodosFuncionarios;
    private javax.swing.JComboBox<String> comboStatusSalario;
    private com.toedter.calendar.JDateChooser dateDataLiberacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelDadosFuncionario;
    private javax.swing.JPanel panelpagamento;
    private javax.swing.JTable tableSalarioFuncionarios;
    // End of variables declaration//GEN-END:variables
}
