/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.FuncionarioController;
import dao.FuncionarioDAO;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;
import util.CampoMoeda;
import util.Criptografia;
import util.SomenteLetras;

/**
 *
 * @author manoelpimentel
 */
public class TelaCadastroFuncionario extends javax.swing.JInternalFrame {

    private final FuncionarioController controller = new FuncionarioController();

    /**
     * Creates new form CadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
        new FuncionarioDAO().atualizarFuncionariosPausados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoConsultarCpf = new javax.swing.JFormattedTextField();
        jRadioListarTodosFuncionarios = new javax.swing.JRadioButton();
        btnConsultar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelDadosFuncionario = new javax.swing.JPanel();
        jLabelFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        campoLogin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateAdmissao = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        ComboCargo = new javax.swing.JComboBox<>();
        campoCPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnAtualizarDados = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelBtn = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDadosFuncionarios = new javax.swing.JTable();

        setClosable(true);
        setTitle("Sistema Hoteleiro - cadastro Funcionario");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Antes de Realizar um Cadastro Consulte o CPF!");

        jLabel2.setText("CPF:");

        try {
            campoConsultarCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jRadioListarTodosFuncionarios.setText("Listar Todos Funcionarios");

        btnConsultar.setBackground(new java.awt.Color(0, 51, 51));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_buscar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 51, 51));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        panelDadosFuncionario.setBackground(new java.awt.Color(153, 153, 153));
        panelDadosFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Funcionario"));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto.png"))); // NOI18N

        jLabel5.setText("Nome Completo:");

        SomenteLetras.aplicarComCapitalizacao(campoNome);

        jLabel7.setText("Telefone:");

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("E-mail:");

        SomenteLetras.aplicarComCapitalizacao(campoLogin);

        jLabel9.setText("Login Usuario:");

        jLabel10.setText("Senha:");

        jLabel11.setText("Salario:");

        jLabel12.setText("Data Admissão:");

        jLabel13.setText("Status:");

        ComboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administração", "Gerente", "Recepcionista", "Porteilro" }));

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("CPF:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "ATIVO", "INATIVO", "PAUSADO" }));

        jLabel4.setText("Cargo:");

        CampoMoeda.aplicar(campoSalario); // Aplica a class que so permite digita valores do tipo moeda brasil

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnFechar.setBackground(new java.awt.Color(0, 51, 51));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_excluir.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 51, 51));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_salvar.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Faça um cadastro ou atualização de dados do funcionario!");

        btnAtualizarDados.setBackground(new java.awt.Color(0, 51, 51));
        btnAtualizarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_salvar.png"))); // NOI18N
        btnAtualizarDados.setText("Atualizar");
        btnAtualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(32, 32, 32)
                .addComponent(btnAtualizarDados)
                .addGap(33, 33, 33)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnCadastrar)
                    .addComponent(jLabel14)
                    .addComponent(btnAtualizarDados))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDadosFuncionarioLayout = new javax.swing.GroupLayout(panelDadosFuncionario);
        panelDadosFuncionario.setLayout(panelDadosFuncionarioLayout);
        panelDadosFuncionarioLayout.setHorizontalGroup(
            panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabelFoto)
                        .addGap(18, 18, 18)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(campoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(campoNome))
                            .addComponent(jLabel7)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboCargo, 0, 180, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(campoSalario))
                        .addGap(57, 57, 57)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateAdmissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        panelDadosFuncionarioLayout.setVerticalGroup(
            panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoLogin)
                                    .addComponent(campoPassword)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDateAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGroup(panelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelDadosFuncionarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStatus)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        panelBtn.setBackground(new java.awt.Color(153, 153, 153));
        panelBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnExcluir.setBackground(new java.awt.Color(0, 51, 51));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 51, 51));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Para editar, excluir um Funcionario selcione na tabela!");

        javax.swing.GroupLayout panelBtnLayout = new javax.swing.GroupLayout(panelBtn);
        panelBtn.setLayout(panelBtnLayout);
        panelBtnLayout.setHorizontalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(34, 34, 34)
                .addComponent(btnExcluir)
                .addGap(23, 23, 23))
        );
        panelBtnLayout.setVerticalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tableDadosFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "CARGO", "STATUS", "SALARIO", "LOGIN", "SENHA", "TELEFONE", "E-MAIL", "DATA ADMISSÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDadosFuncionarios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelDadosFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDadosFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(campoConsultarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jRadioListarTodosFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addGap(52, 52, 52)
                .addComponent(btnLimpar)
                .addGap(60, 60, 60))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioListarTodosFuncionarios)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar)
                    .addComponent(campoConsultarCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherTabela(List<Funcionario> lista) {
        DefaultTableModel model = (DefaultTableModel) tableDadosFuncionarios.getModel();
        model.setRowCount(0);
        for (Funcionario f : lista) {
            model.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCpf(),
                f.getCargo(),
                f.getStatus(),
                f.getSalario(),
                f.getLogin(),
                "********",
                f.getTelefone(),
                f.getEmail(),
                f.getDataAdmissao()
            });
        }
    }

    // cada ação realizada aqui manter historico por exemplo: cadastro, edição, excluir etc... 
    // tera uma tela pra ver o historico de funcionario Ativo, inativo e pausado
    private boolean validarCamposObrigatorios() {
        if (campoNome.getText().trim().isEmpty()
                || campoCPF.getText().trim().equals("   .   .   -  ")
                || campoLogin.getText().trim().isEmpty()
                || campoPassword.getPassword().length == 0
                || ComboCargo.getSelectedIndex() == 0
                || comboStatus.getSelectedIndex() == 0
                || jDateAdmissao.getDate() == null
                || campoSalario.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos obrigatórios!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    //usado no atualizar
    private boolean validarCamposObrigatoriosAtualizacao() {
        if (campoNome.getText().trim().isEmpty()
                || campoCPF.getText().trim().isEmpty()
                || campoLogin.getText().trim().isEmpty()
                || campoEmail.getText().trim().isEmpty()
                || campoTelefone.getText().trim().isEmpty()
                || ComboCargo.getSelectedIndex() == 0
                || comboStatus.getSelectedIndex() == 0
                || jDateAdmissao.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos obrigatórios (exceto senha).");
            return false;
        }
        return true;
    }

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        try {
            if (jRadioListarTodosFuncionarios.isSelected()) {
                preencherTabela(controller.listarTodos());
            } else {
                String cpf = campoConsultarCpf.getText();
                if (cpf.trim().equals("   .   .   -  ")) {
                    JOptionPane.showMessageDialog(this,
                            "Informe um CPF para consultar!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Funcionario f = controller.buscarPorCpf(cpf);
                if (f != null) {
                    preencherTabela(List.of(f));
                } else {
                    JOptionPane.showMessageDialog(this, "Funcionário não encontrado!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro na consulta: " + e.getMessage());
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linha = tableDadosFuncionarios.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um funcionário na tabela para editar!");
            return;
        }

        try {
            campoNome.setText(tableDadosFuncionarios.getValueAt(linha, 1).toString());
            campoCPF.setText(tableDadosFuncionarios.getValueAt(linha, 2).toString());
            ComboCargo.setSelectedItem(tableDadosFuncionarios.getValueAt(linha, 3).toString());
            comboStatus.setSelectedItem(tableDadosFuncionarios.getValueAt(linha, 4).toString());
            campoSalario.setText(tableDadosFuncionarios.getValueAt(linha, 5).toString());
            campoLogin.setText(tableDadosFuncionarios.getValueAt(linha, 6).toString());
            campoTelefone.setText(tableDadosFuncionarios.getValueAt(linha, 8).toString());
            campoEmail.setText(tableDadosFuncionarios.getValueAt(linha, 9).toString());

            // Conversão segura da data
            String dataStr = tableDadosFuncionarios.getValueAt(linha, 10).toString();
            if (dataStr != null && !dataStr.isEmpty()) {
                LocalDate localDate = LocalDate.parse(dataStr);
                jDateAdmissao.setDate(java.sql.Date.valueOf(localDate));
            } else {
                jDateAdmissao.setDate(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher os campos: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:                                         

        int linha = tableDadosFuncionarios.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um funcionário para excluir!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Deseja realmente excluir este funcionário?\n"
                + "Se ele tiver pagamentos, será colocado como PAUSADO.",
                "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {

            int id = (int) tableDadosFuncionarios.getValueAt(linha, 0);

            controller.excluir(id);

            JOptionPane.showMessageDialog(this,
                    "Operação realizada com sucesso!\n"
                    + "Se existiam pagamentos, o funcionário foi PAUSADO.");

            preencherTabela(controller.listarTodos());
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if (!validarCamposObrigatorios()) {
            return;
        }

        try {
            String cpfSemMascara = campoCPF.getText().replaceAll("\\D", "");

            // Verifica duplicidade de CPF
            if (controller.existePorCpf(cpfSemMascara)) {
                JOptionPane.showMessageDialog(this,
                        "Já existe um funcionário cadastrado com este CPF!",
                        "Duplicidade de CPF", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Funcionario f = new Funcionario();
            f.setNome(campoNome.getText());
            //f.setCpf(campoCPF.getText());
            // Remove máscara e define o CPF sem pontos e traço
            f.setCpf(campoCPF.getText().replaceAll("\\D", ""));

            f.setCargo(ComboCargo.getSelectedItem().toString());
            f.setEmail(campoEmail.getText());
            f.setTelefone(campoTelefone.getText());
            f.setLogin(campoLogin.getText());
            f.setSenha(Criptografia.gerarHash(new String(campoPassword.getPassword())));
            f.setStatus(comboStatus.getSelectedItem().toString().toUpperCase());
            f.setRoleId(Funcionario.obterRoleIdPorCargo(ComboCargo.getSelectedItem().toString()));
            f.setDataAdmissao(jDateAdmissao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            f.setSalario(CampoMoeda.getValor(campoSalario));

            controller.inserir(f);

            JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
            limparCampos();
            preencherTabela(controller.listarTodos());// Exibe o funcionario na tabela
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar funcionário: " + e.getMessage());
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarDadosActionPerformed
        // TODO add your handling code here:
        try {
            if (!validarCamposObrigatoriosAtualizacao()) {
                return;
            }

            int linha = tableDadosFuncionarios.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um funcionário para atualizar.");
                return;
            }

            Funcionario f = new Funcionario();
            f.setId(Integer.parseInt(tableDadosFuncionarios.getValueAt(linha, 0).toString()));
            f.setNome(campoNome.getText().trim());
            f.setCpf(campoCPF.getText().replaceAll("\\D", "")); // remove máscara
            f.setCargo(ComboCargo.getSelectedItem().toString());
            f.setEmail(campoEmail.getText().trim());
            f.setTelefone(campoTelefone.getText().trim());
            f.setLogin(campoLogin.getText().trim());
            f.setStatus(comboStatus.getSelectedItem().toString());
            f.setRoleId(Funcionario.obterRoleIdPorCargo(ComboCargo.getSelectedItem().toString()));
            f.setDataAdmissao(jDateAdmissao.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            f.setSalario(CampoMoeda.getValor(campoSalario));

            // Atualiza a senha somente se o campo foi preenchido
            String novaSenha = new String(campoPassword.getPassword()).trim();
            if (!novaSenha.isEmpty()) {
                f.setSenha(Criptografia.gerarHash(novaSenha));
            } else {
                // Mantém a senha atual
                Funcionario existente = controller.buscarPorId(f.getId());
                if (existente != null) {
                    f.setSenha(existente.getSenha());
                }
            }

            // Chama o controller para atualizar
            controller.atualizar(f);

            JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            preencherTabela(controller.listarTodos());

            // Atualiza usuário logado (sincroniza TelaPrincipal)
            Funcionario logado = util.UsuarioLogado.getUsuario();
            if (logado != null && logado.getId() == f.getId()) {
                util.UsuarioLogado.setUsuario(f);
            }

            // Limpar os campos depois da ação
            limparCampos();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao atualizar funcionário: " + e.getMessage());
        }

    }//GEN-LAST:event_btnAtualizarDadosActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        dispose(); // Fechar a tela
    }//GEN-LAST:event_btnFecharActionPerformed

    private void limparCampos() {

        campoNome.setText("");
        campoCPF.setValue(null);
        campoEmail.setText("");
        campoTelefone.setValue(null);
        campoLogin.setText("");
        campoPassword.setText("");
        campoSalario.setText("");
        ComboCargo.setSelectedIndex(0);
        comboStatus.setSelectedIndex(0);
        jDateAdmissao.setDate(null);
        campoConsultarCpf.setText("");
        jRadioListarTodosFuncionarios.setSelected(false);

        // Limpa o camp de buscar
        // Limpa todas as linhas da tabela
        /*DefaultTableModel model = (DefaultTableModel) tableDadosFuncionarios.getModel();
        model.setRowCount(0);*/
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCargo;
    private javax.swing.JButton btnAtualizarDados;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoConsultarCpf;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JComboBox<String> comboStatus;
    private com.toedter.calendar.JDateChooser jDateAdmissao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioListarTodosFuncionarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelDadosFuncionario;
    private javax.swing.JTable tableDadosFuncionarios;
    // End of variables declaration//GEN-END:variables
}
