/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import util.SomenteLetras;
import util.SomenteNumeros;

import controller.QuartoController;
import model.Quarto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Date;

/**
 *
 * @author manoelpimentel
 */
public class TelaCadastrarLimpeza extends javax.swing.JInternalFrame {

    private final QuartoController quartoController = new QuartoController();
    private Quarto quartoSelecionado = null;

    /**
     * Creates new form CadastrarLimpeza
     */
    public TelaCadastrarLimpeza() {
        initComponents();
    }

    private void preencherTabelaQuarto(List<Quarto> lista) {
        DefaultTableModel model = (DefaultTableModel) tabelDadosQuarto.getModel();
        model.setRowCount(0);

        for (Quarto q : lista) {
            model.addRow(new Object[]{
                q.getId(),
                q.getNumero(),
                q.getTipo(),
                q.getStatus(),
                q.getNumCamas(),
                q.getCriadoEm() != null ? q.getCriadoEm() : "—",
                q.getObservacao()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        numQuarto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboQuartoLimpo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboRoupaCama = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboInsumoRepostos = new javax.swing.JComboBox<>();
        dataLimpeza = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btnRegistrarLimpeza = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboStatusQuarto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CampoNumQuarto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarNovoStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDadosQuarto = new javax.swing.JTable();
        btnConsultarQuarto = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sistema Hoteleiro - Cadastro Manutenção");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Para registrar ou atualizar o status do quarto realize um buscar informando o numero do quarto!");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Dados da Limpeza"));

        SomenteNumeros.aplicar(numQuarto);

        jLabel4.setText("Nº Quarto:");

        jLabel5.setText("Quarto foi limpo?");

        comboQuartoLimpo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jLabel6.setText("Troca de roupa de  cama?");

        comboRoupaCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jLabel7.setText("Insumos repostos?");

        comboInsumoRepostos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));

        jLabel8.setText("Data limpeza:");

        btnRegistrarLimpeza.setBackground(new java.awt.Color(0, 51, 51));
        btnRegistrarLimpeza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_salvar.png"))); // NOI18N
        btnRegistrarLimpeza.setText("Registrar Limpeza");
        btnRegistrarLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLimpezaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 51, 51));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_excluir.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(0, 51, 51));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_excluir.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        SomenteLetras.aplicarComCapitalizacao(campoNome);

        jLabel9.setText("Nome Funcionario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(numQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(comboQuartoLimpo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboInsumoRepostos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(comboRoupaCama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataLimpeza, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(117, 117, 117)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarLimpeza, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboRoupaCama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataLimpeza, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboQuartoLimpo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboInsumoRepostos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnRegistrarLimpeza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar Novo Status Quarto"));

        comboStatusQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Disponível", "Bloqueado" }));

        jLabel3.setText("Status:");

        SomenteNumeros.aplicar(CampoNumQuarto);

        jLabel2.setText("Informe o numero do quarto:");

        btnRegistrarNovoStatus.setBackground(new java.awt.Color(0, 51, 51));
        btnRegistrarNovoStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_bot_salvar.png"))); // NOI18N
        btnRegistrarNovoStatus.setText("Registrar Novo Status");
        btnRegistrarNovoStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNovoStatusActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        tabelDadosQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NUM. QUARTO", "TIPO", "STATUS", "NUM. CAMAS", "CRIADO EM", "OBSERVAÇÕES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelDadosQuarto);

        btnConsultarQuarto.setBackground(new java.awt.Color(0, 51, 51));
        btnConsultarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_buscar.png"))); // NOI18N
        btnConsultarQuarto.setText("Buscar Quarto");
        btnConsultarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarQuartoActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(0, 51, 51));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboStatusQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarNovoStatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(btnConsultarQuarto)
                        .addGap(40, 40, 40)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarQuarto)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatusQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarNovoStatus))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarQuartoActionPerformed
        // TODO add your handling code here:
        /**
         * Ação: Vai consulta no um quarto pelo numero e trazer as informação
         * dele como: ID, NUMERO, TIPO, STATUS, NUMERO CAMAS, CRADO EM, E
         * OBSERVAÇÃO.
         */
        try {
            if (CampoNumQuarto.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Informe o número do quarto.");
                return;
            }

            int numero = Integer.parseInt(CampoNumQuarto.getText().trim());
            Quarto q = quartoController.buscarPorNumero(numero);

            if (q == null) {
                JOptionPane.showMessageDialog(this, "Quarto não encontrado.");
                return;
            }

            quartoSelecionado = q;
            preencherTabelaQuarto(List.of(q));

            // Pré-preenche campo do registro de limpeza
            numQuarto.setText(String.valueOf(q.getNumero()));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número do quarto inválido.");
        }

    }//GEN-LAST:event_btnConsultarQuartoActionPerformed

    private void btnRegistrarNovoStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNovoStatusActionPerformed
        // TODO add your handling code here:
        /**
         * Corrigir aqui as seguinte codições só vai atualizar o status se o usuario selecionar na tabela o quarto.
         * Usuario selecionar => preenche o combo => e clicar no btnRegistrarNovoStatus
         * já esta consultando e atualizando só falta corrigir esse detalhe.
         */
        if (quartoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um quarto primeiro.");
            return;
        }

        if (comboStatusQuarto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um novo status.");
            return;
        }

        String novoStatus = comboStatusQuarto.getSelectedItem().toString().toUpperCase();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente alterar o status do quarto?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        quartoSelecionado.setStatus(novoStatus);

        if (quartoController.atualizarQuarto(quartoSelecionado)) {
            JOptionPane.showMessageDialog(this, "Status do quarto atualizado com sucesso!");
            preencherTabelaQuarto(List.of(quartoSelecionado));
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar status.");
        }

        /**
         * Ação: Usuario após realizar a consultar e encontrar o quarto ele
         * selecionar na tabela e atualiza o novo status do quarto no
         * comboStatusQuarto e clica no btnRegistrarNovoStatus
         */
    }//GEN-LAST:event_btnRegistrarNovoStatusActionPerformed

    private void btnRegistrarLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLimpezaActionPerformed
        // TODO add your handling code here:
        if (numQuarto.getText().isBlank() || campoNome.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios.");
            return;
        }

        if (comboQuartoLimpo.getSelectedIndex() == 0
                || comboRoupaCama.getSelectedIndex() == 0
                || comboInsumoRepostos.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione todas as opções.");
            return;
        }

        Date data = dataLimpeza.getDate();
        if (data == null) {
            JOptionPane.showMessageDialog(this, "Informe a data da limpeza.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Deseja registrar a limpeza deste quarto?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // AQUI entra seu LimpezaController futuramente
        // limpezaController.registrar(...)
        JOptionPane.showMessageDialog(this, "Limpeza registrada com sucesso!");

        btnLimparActionPerformed(null);

        /**
         * Ação: Vai regstra uma limpeza onde usuario informa os dados do quarto
         * e registra a limpeza.
         * Ao tentar fazer o registro de uma limpeza vai validade de o ususrio preencheu o comboStatusQuarto
         * antes de finalizar. se o usuario não tiver preenchido aparecer a mensagem.
         * e o usuario deve ter preenchido todos os campos como: comboStatusQuarto,
         * numQuarto, comboQuartoLimpo, comboRoupaCama, campoNome, comboInsumoRepostos, dataLimpeza
         */
    }//GEN-LAST:event_btnRegistrarLimpezaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(
                this,
                "Deseja cancelar a operação?",
                "Cancelar",
                JOptionPane.YES_NO_OPTION
        );

        if (op == JOptionPane.YES_OPTION) {
            btnLimparActionPerformed(null);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        /**
         * Limpa os campos da tela
         */
        CampoNumQuarto.setText("");
        numQuarto.setText("");
        campoNome.setText("");

        comboQuartoLimpo.setSelectedIndex(0);
        comboRoupaCama.setSelectedIndex(0);
        comboInsumoRepostos.setSelectedIndex(0);
        comboStatusQuarto.setSelectedIndex(0);

        dataLimpeza.setDate(null);

        ((DefaultTableModel) tabelDadosQuarto.getModel()).setRowCount(0);

        quartoSelecionado = null;

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        dispose(); // Fechar a tela
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoNumQuarto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarQuarto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrarLimpeza;
    private javax.swing.JButton btnRegistrarNovoStatus;
    private javax.swing.JTextField campoNome;
    private javax.swing.JComboBox<String> comboInsumoRepostos;
    private javax.swing.JComboBox<String> comboQuartoLimpo;
    private javax.swing.JComboBox<String> comboRoupaCama;
    private javax.swing.JComboBox<String> comboStatusQuarto;
    private com.toedter.calendar.JDateChooser dataLimpeza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numQuarto;
    private javax.swing.JTable tabelDadosQuarto;
    // End of variables declaration//GEN-END:variables
}
